### ISSUE TITLE
Need to make demo site more responsive on mobile

### ISSUE THREAD

**Issue by Edmund1645** [Edmund1645/vue-transitions-css#2]

**Comment by simeon4real** [comment]
Still needed?

**Comment by Edmund1645** [comment]
Yes, very much.

**Comment by simeon4real** [comment]
About this... Can I change some of the design? Like improve it? The links in the header can go to the bottom. It'll be responsive as well.

**Comment by Edmund1645** [comment]
Oh yeah, any improvement is welcome, i would love the Github link to point
back to the repository, the Twitter can be taken out.

**Comment by simeon4real** [comment]
Okay. I'll get working on it. Expect my PR soon 😊
